#!/bin/bash

#this was obtained by attatching strace to steam and then launching ADOFAI in forced capatibility mode with Proton 10.0 selected then examaning all of the changed environmental variables

shadercachedir="/home/birb/Projects/Archipelago-Organiser/manual/fake-library/shadercache/9777950"
mkdir "$shadercachedir"
mkdir "$shadercachedir/fozpipelinesv6"
mkdir "$shadercachedir/nvidiav1"
mkdir "$shadercachedir/AMDv1"
mkdir "$shadercachedir/fozmediav1"
mkdir "$shadercachedir/DXVK_state_cache"


export SDL_VIDEO_X11_DGAMOUSE="0"
export TEXTDOMAINDIR="/usr/share/locale"
export STEAM_RUNTIME=""
export SYSTEM_LD_LIBRARY_PATH=""
export PWD="/home/birb/.local/share/Steam"
export STEAM_ZENITY="/usr/bin/zenity"
export SYSTEM_PATH="/home/birb/.local/share/pnpm:/home/birb/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/birb/Vivado/2025.2/Vivado/bin/:/home/birb/.cargo/bin"
export SRT_LOG_TO_JOURNAL="0"
export STEAMSCRIPT_VERSION="1.0.0.85"
export XDG_ACTIVATION_TOKEN="kwin-76"
export SRT_LOGGER_USE_JOURNAL="1"
export STEAMSCRIPT="/usr/lib/steam/steam"
export SRT_LOG_LEVEL_PREFIX="1"
export SYSTEM_ZENITY="/usr/bin/zenity"
export PATH="/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/bin:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/bin:/home/birb/.local/share/pnpm:/home/birb/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/cuda/bin:/var/lib/flatpak/exports/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/birb/Vivado/2025.2/Vivado/bin/:/home/birb/.cargo/bin"
export OLDPWD="/home/birb/.local/share/Steam"
export STEAM_RUNTIME_LIBRARY_PATH="/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/opt/cuda/lib64:/opt/cuda/nvvm/lib64:/usr/lib32:/usr/lib/perf:/usr/lib/libfakeroot:/usr/lib:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib"
export TEXTDOMAIN="steam"
export _="/home/birb/.local/share/Steam/ubuntu12_32/steam"
export BREAKPAD_DUMP_LOCATION="/tmp/dumps"
export STEAM_BASE_FOLDER="/home/birb/.local/share/Steam"
export Steam3Master="127.0.0.1:57343"
export SteamUser="nat_than"
export STEAMVIDEOTOKEN="92276
32f5h290g53047gv5034nbvt923b
"
export SteamClientLaunch="1"
export ENABLE_VK_LAYER_VALVE_steam_overlay_1="1"
export EnableConfiguratorSupport="4096"
export SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD="1"
export SDL_GAMECONTROLLER_IGNORE_DEVICES="0x2dc8/0x6000,0x2dc8/0x6100,0x2dc8/0x6001,0x2dc8/0x6101,0x2dc8/0x6003,0x2dc8/0x6006,0x2dc8/0x6009,0x2dc8/0x6012,0x28de/0x1002,0x28de/0x1003,0x28de/0x1071,0x28de/0x1052,0x28de/0x1042,0x28de/0x1203,0x28de/0x1204,0x28de/0x1205,0x28de/0x1206,0x28de/0x1302,0x28de/0x1303,0x28de/0x1304,0x28de/0x1305,0x0f0d/0x01ab,0x0f0d/0x0196,0x28de/0x12ff,0x28de/0x12fe,0x28de/0x12fd,0x28de/0x12fc,0x28de/0x12fb,0x28de/0x12fa,0x28de/0x12f9,0x28de/0x12f8,0x28de/0x12f7,0x28de/0x12f6,0x28de/0x12f5,0x28de/0x12f4,0x28de/0x12f3,0x28de/0x12f2,0x28de/0x12f1,0x28de/0x12f0,0x28DE/0x11E0,0x0000/0x11fb,0x28de/0x1101,0x28de/0x1102,0x28de/0x1105,0x28de/0x1106,0x28de/0x1142,0x28de/0x1201,0x28de/0x1202,0x28de/0x1205,0x28de/0x1220,0x28de/0x1302,0x28de/0x1303,0x28de/0x1304,0x28de/0x1305,"
export SDL_JOYSTICK_HIDAPI_STEAMXBOX="0"
export DISABLE_LAYER_AMD_SWITCHABLE_GRAPHICS_1="1"
export SteamGameId="977950"
export SteamAppId="977950"
export SteamOverlayGameId="977950"
export SteamAppUser="nat_than"
export MESA_GLSL_CACHE_DIR="$shadercachedir"
export MESA_GLSL_CACHE_MAX_SIZE="5G"
export __GL_SHADER_DISK_CACHE_PATH="$shadercachedir/nvidiav1"
export __GL_SHADER_DISK_CACHE_APP_NAME="steamapp_shader_cache"
export __GL_SHADER_DISK_CACHE_READ_ONLY_APP_NAME="steam_shader_cache;steamapp_merged_shader_cache"
export __GL_SHADER_DISK_CACHE_SKIP_CLEANUP="1"
export AMD_VK_PIPELINE_CACHE_PATH="$shadercachedir/AMDv1"
export AMD_VK_PIPELINE_CACHE_FILENAME="steamapp_shader_cache"
export AMD_VK_USE_PIPELINE_CACHE="1"
export STEAM_FOSSILIZE_DUMP_PATH="$shadercachedir/fozpipelinesv6/steamapprun_pipeline_cache"
export STEAM_FOSSILIZE_DUMP_PATH_READ_ONLY="$bucketdir/steam_pipeline_cache.foz;$bucketdir/steamapp_pipeline_cache.foz"
export FOSSILIZE_APPLICATION_INFO_FILTER_PATH="/home/birb/.local/share/Steam/fossilize_engine_filters.json"
export ENABLE_VK_LAYER_VALVE_steam_fossilize_1="1"
export STEAM_COMPAT_MEDIA_PATH="$shadercachedir/fozmediav1"
export STEAM_COMPAT_TRANSCODED_MEDIA_PATH="$shadercachedir"
export MESA_SHADER_CACHE_DIR="$shadercachedir"
export MESA_SHADER_CACHE_MAX_SIZE="5G"
export MESA_DISK_CACHE_SINGLE_FILE="1"
export MESA_DISK_CACHE_READ_ONLY_FOZ_DBS="steam_cache,steam_precompiled,steam_precompiled_904f69d2b1b44b65,steam_precompiled_2e6c105801134e9c"
export DXVK_STATE_CACHE_PATH="$shadercachedir/DXVK_state_cache"
export STEAM_COMPAT_APP_ID="977950"
export STEAM_COMPAT_PROTON="1"
export STEAM_COMPAT_TOOL_PATHS="/home/birb/Projects/Archipelago-Organiser/manual/proton-10.0"
export STEAM_COMPAT_LIBRARY_PATHS="/home/birb/Projects/Archipelago-Organiser/manual/fake-library"
export STEAM_COMPAT_SHADER_PATH="$shadercachedir"
export STEAM_COMPAT_INSTALL_PATH="/home/birb/Projects/Archipelago-Organiser/manual/fake-library/common/adofai-older"
export STEAM_COMPAT_MOUNTS="/home/birb/Projects/Archipelago-Organiser/manual/proton-10.0"
export STEAM_COMPAT_DATA_PATH="/home/birb/Projects/Archipelago-Organiser/manual/fake-library/compatdata/9777950"
export STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/birb/.local/share/Steam"
export PROTON_CRASH_REPORT_DIR="/tmp/proton_crashreports"
export SteamVirtualGamepadInfo_Proton="/home/birb/.local/share/Steam/config/virtualgamepadinfo.txt"
export LC_ALL="C"
export SteamEnv="1"
export SRT_LAUNCHER_SERVICE_ALONGSIDE_STEAM="com.steampowered.PressureVessel.LaunchAlongsideSteam"
export STEAM_COMPAT_FLAGS="search-cwd"
export LD_LIBRARY_PATH="/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_32:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/pinned_libs_64:/opt/cuda/lib64:/opt/cuda/nvvm/lib64:/usr/lib32:/usr/lib/perf:/usr/lib/libfakeroot:/usr/lib:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/lib:/home/birb/.local/share/Steam/ubuntu12_32/steam-runtime/usr/lib:/mnt/ssd1/steam/steamapps/common/A Dance of Fire and Ice"
export LD_PRELOAD=":/home/birb/.local/share/Steam/ubuntu12_64/gameoverlayrenderer.so"
export STEAM_CLIENT_CONFIG_FILE="/home/birb/.local/share/steam.cfg"

'/home/birb/Projects/Archipelago-Organiser/manual/proton-10.0/proton' waitforexitandrun  '/home/birb/Projects/Archipelago-Organiser/manual/fake-library/common/adofai-older/A Dance of Fire and Ice.exe'
